// Generated by scripts/generate-session-extensions.mjs from OpenAPI. Do not edit.
import { APIResource } from '../resource';
import type { APIPromise } from '../api-promise';
import type { RequestOptions } from '../internal/request-options';
export type UserMemory = { enabled: boolean; profile: string; revision: number; updatedAt: string | null };
export type UserMemoryUpdateParams = {
  expectedRevision: number;
  requestId: string;
  profile?: string;
  enabled?: boolean;
};
export type UserMemoryClearParams = { expectedRevision: number; requestId: string };
export type SessionUserMemoryUpdateParams = { expectedRevision: number; requestId: string; profile: string };
export class UserMemories extends APIResource {
  retrieve(options?: RequestOptions): APIPromise<UserMemory> {
    return this._client.get(`/v1/user-memory`, { ...options });
  }
  update(body: UserMemoryUpdateParams, options?: RequestOptions): APIPromise<UserMemory> {
    return this._client.patch(`/v1/user-memory`, { body, ...options });
  }
  clear(body: UserMemoryClearParams, options?: RequestOptions): APIPromise<UserMemory> {
    return this._client.delete(`/v1/user-memory`, { body, ...options });
  }
}
export class SessionUserMemory extends APIResource {
  retrieve(sessionId: string, options?: RequestOptions): APIPromise<UserMemory> {
    return this._client.get(`/v1/sessions/${encodeURIComponent(sessionId)}/user-memory`, { ...options });
  }
  update(
    sessionId: string,
    body: SessionUserMemoryUpdateParams,
    options?: RequestOptions,
  ): APIPromise<UserMemory> {
    return this._client.patch(`/v1/sessions/${encodeURIComponent(sessionId)}/user-memory`, {
      body,
      ...options,
    });
  }
}
