configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tembo%2Ftembo-81ef34f8ae80f8570ca7dff1bf42542bbffb6e980b7bda4a8f6ff28b7dc0a792.yml
openapi_spec_hash: fee76ea9e9c45cbfb6d22da9cae843bd
config_hash: 8fba1d45a848bce88e9564ab8a960838
