configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tembo%2Ftembo-0ebc2acf311d7b259a04bddae10dee90e5f48481af0ba7ce18b4b9e1a5dd0e2a.yml
openapi_spec_hash: e9dc1aace4dccd368caaf91da7cbd68d
config_hash: 8fba1d45a848bce88e9564ab8a960838
