configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tembo%2Ftembo-0baf6d5fac85a1629bbaab8ed21fa4ff6e5b8cb9dd44dd88aa54171842ca385c.yml
openapi_spec_hash: b59ac5619d3a3279b3afa3bdc0adbf88
config_hash: 8fba1d45a848bce88e9564ab8a960838
