// Hand-written, not generated by Scalar: keep this file when regenerating the SDK.

import { APIError, APIUserAbortError } from '../../../core/error';
import type { Live } from './live';

export interface LiveSubscribeParams {
  /** The session whose message changes to follow. */
  sessionId: string;
}

export interface LiveSubscribeOptions {
  /** Stops the subscription and closes the connection when aborted. */
  signal?: AbortSignal | undefined;
  /** Consecutive failed connection attempts before giving up. Default: 5. */
  maxRetries?: number | undefined;
  /** Initial backoff delay in milliseconds. Default: 500. */
  initialDelay?: number | undefined;
  /** Maximum backoff delay in milliseconds. Default: 8000. */
  maxDelay?: number | undefined;
}

/**
 * Follows a session's message changes, reconnecting as needed. Live tickets are single-use and
 * expire after 30 seconds, so each connection is authorized with a fresh ticket.
 *
 * Yields each frame the server sends: `{ type: 'ready' }` after every (re)connect, when callers
 * should re-read messages to catch anything missed, then `{ resource: 'message', sessionId }`
 * whenever the session's messages change. Ends when `signal` aborts or the loop exits, and throws
 * if access is refused (a 4xx other than 429) or connecting keeps failing.
 */
/** Waits for `ms`, resolving early (and clearing the timer) if `signal` aborts. */
function backoff(ms: number, signal: AbortSignal | undefined): Promise<void> {
  return new Promise((resolve) => {
    if (signal?.aborted) return resolve();
    const done = () => {
      clearTimeout(timer);
      signal?.removeEventListener('abort', done);
      resolve();
    };
    const timer = setTimeout(done, ms);
    signal?.addEventListener('abort', done, { once: true });
  });
}

export async function* subscribe(
  live: Live,
  params: LiveSubscribeParams,
  options: LiveSubscribeOptions = {},
): AsyncGenerator<unknown, void, undefined> {
  const { signal, maxRetries = 5, initialDelay = 500, maxDelay = 8000 } = options;
  let failures = 0;
  while (!signal?.aborted) {
    let ticket: string;
    try {
      ({ ticket } = await live.authorize({ scope: { sessionId: params.sessionId } }, { signal }));
    } catch (error) {
      if (error instanceof APIUserAbortError || signal?.aborted) return;
      const refused =
        error instanceof APIError &&
        error.status !== undefined &&
        error.status >= 400 &&
        error.status < 500 &&
        error.status !== 429;
      if (refused || ++failures > maxRetries) throw error;
      await backoff(Math.min(initialDelay * 2 ** (failures - 1), maxDelay), signal);
      continue;
    }

    // The abort may have fired while authorization finished, before the listener below exists.
    if (signal?.aborted) return;
    const connection = live.connect({ ticket });
    const close = () => connection.close();
    signal?.addEventListener('abort', close, { once: true });
    try {
      for await (const event of connection) {
        if (event.type === 'message') {
          const frame = event.message;
          if (frame && typeof frame === 'object' && 'type' in frame && frame.type === 'ready') failures = 0;
          yield frame;
        } else if (event.type === 'close') {
          break;
        }
      }
    } finally {
      signal?.removeEventListener('abort', close);
      connection.close();
    }
    if (signal?.aborted) return;
    if (++failures > maxRetries)
      throw new Error(`Live message connection failed after ${maxRetries} retries`);
    await backoff(Math.min(initialDelay * 2 ** (failures - 1), maxDelay), signal);
  }
}
